// 상단 헤더 + 삼선 메뉴 이동 (하단 탭바 제거)
const {boot,ok,done,HTML}=require('./harness');
const fs=require('fs'),path=require('path');
const b=boot();const els=b.dev.els;
b.X.render();
const items=[...els.menu.innerHTML.matchAll(/<button[^>]*onclick="go\('(\w+)'\)"[^>]*>([^<]*)</g)].map(m=>m[1]);
ok('메뉴 항목 4개, 순서: 추천 → 내 카드 → 기록 → (맨 아래) 데이터·계정',JSON.stringify(items)==='["rec","cards","log","data"]',items.join(','));
ok('데이터·계정 항목은 구분선(sep)으로 분리',/class="[^"]*sep[^"]*"[^>]*onclick="go\('data'\)"/.test(els.menu.innerHTML));
ok('현재 화면 항목 강조(on), 헤더에 현재 화면 이름',/class="on"[^>]*onclick="go\('rec'\)"/.test(els.menu.innerHTML)&&els.pg.textContent==='추천',els.pg.textContent);
ok('처음엔 메뉴 닫힘',els.menu.hidden===true||els.menu.hidden===undefined);
const run=c=>require('vm').runInContext(c,b.ctx);
run('toggleMenu()');ok('삼선 클릭 → 메뉴 열림 + 배경막',els.menu.hidden===false&&els.scrim.hidden===false);
run('toggleMenu()');ok('다시 누르면 닫힘',els.menu.hidden===true&&els.scrim.hidden===true);
run('toggleMenu()');run("go('cards')");
ok('항목 선택 → 화면 이동 + 메뉴 자동 닫힘',run('tab')==='cards'&&els.menu.hidden===true&&els.pg.textContent==='내 카드');
ok('이동한 화면이 실제로 렌더됨',/내 카드 · 실적 입력/.test(els.app.innerHTML));
run("go('data')");
ok('데이터·계정 화면 이동: 헤더 라벨',els.pg.textContent==='데이터 · 계정',els.pg.textContent);
ok('데이터·계정 화면 내용: 계정/동기화, Gemini 키, 백업·복원, 초기화',/계정 · 동기화/.test(els.app.innerHTML)&&/Gemini API 키/.test(els.app.innerHTML)&&/백업\(JSON 복사\)/.test(els.app.innerHTML)&&/모든 데이터 초기화/.test(els.app.innerHTML));
ok('내 카드 화면에서는 데이터 섹션이 빠짐',(()=>{run("go('cards')");return !/Gemini API 키/.test(els.app.innerHTML)&&!/백업\(JSON 복사\)/.test(els.app.innerHTML)&&/신한카드 EV/.test(els.app.innerHTML)})());
run("go('log')");ok('기록 화면 이동',/결제 기록/.test(els.app.innerHTML)&&els.pg.textContent==='기록');
run("go('rec')");ok('추천 화면 복귀',/어떤 카드로 결제할까/.test(els.app.innerHTML));
ok('하단 탭바(nav) 제거됨',!/<nav\b/.test(HTML)&&!/nav\{position:fixed/.test(HTML));
ok('헤더에 앱 이름 + 삼선 버튼(접근성 라벨)',/<header class="top">/.test(HTML)&&/카드픽/.test(HTML.match(/<header[\s\S]*?<\/header>/)[0])&&/aria-label="메뉴"/.test(HTML));
const man=JSON.parse(fs.readFileSync(path.join(__dirname,'..','manifest.json'),'utf8'));
ok('manifest 이름이 앱 이름과 일치',/카드픽/.test(man.name)&&man.short_name==='카드픽');
ok('<title>/iOS 앱 이름 일치',/<title>카드픽<\/title>/.test(HTML)&&/apple-mobile-web-app-title" content="카드픽"/.test(HTML));
ok('내용이 하단 탭바 여백(90px)을 더 이상 안 씀',!/padding:16px 16px 90px/.test(HTML));
process.exit(done('nav')?1:0);
